---
- name: Add and manage users on hosts
  hosts: all
  become: true

  roles:
    - bouncmpe.automated.manage_users

  vars:
    usergroups: ["sudo", "users"]
    users:
      - name: dulus1
        groups: ["sudo", "users"]
        ssh_import_id:
          - gh:doganulus

      - name: dulus2
        groups: ["users"]
        ssh_import_id:
          - gh:doganulus