---
- name: Manage users
  hosts: all
  become: true

  tasks:
    - name: Manage users
      ansible.builtin.include_role:
        name: bouncmpe.automated.manage_users

    - name: Manage quotas
      ansible.builtin.include_role:
        name: bouncmpe.automated.manage_quotas

  vars:
    automated_config_home_src: LABEL=/home
    automated_config_home_directory: /home
    automated_config_home_enable_quotas: true
    automated_config_groups: ["sudo", "users", "docker", "kvm"]
    automated_config_users:
      - name: dulus
        groups: ["sudo"]
        ssh_import_id:
          - gh:doganulus
        sudoers:
          nopassword: true

      - name: dogan.ulus
        groups: ["users"]
        ssh_import_id:
          - gh:doganulus
        disk_quota_gb: 100
