- name: Manage usergroups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ usergroups }}"

- name: Manage users
  ansible.builtin.include_tasks:
    file: single_user.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: user

- name: Determine existing users
  shell: 'grep users /etc/group | cut -d: -f4 | tr "," "\n"'
  changed_when: false
  register: existing_users
