- name: Ensure cluster-user group exists
  ansible.builtin.group:
    name: "{{ users_group }}"
    state: present

- name: Manage users
  ansible.builtin.include_role:
    name: bouncmpe.automate.manage_single_user
  vars:
    username: "{{ item.name }}"
    usergroups: "{{ item.groups | default(users_group) }}"
    state: "{{ item.state | default('present') }}"
    remove: "{{ item.remove | default(false) }}"
    ssh_import_id: "{{ item.ssh_import_id }}"
  loop: "{{ users }}"
