# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/group_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html
---
- name: Add the user {{ user.name }}
  ansible.builtin.user:
    name: "{{ user.name }}"
    home: "/home/{{ user.name }}"
    groups: "{{ user.groups | default(default_user_groups) }}"
    append: false
    generate_ssh_key: true
    ssh_key_type: "ed25519"
    ssh_key_file: ".ssh/id_ed25519"
    password_lock: true
    create_home: true
    shell: /bin/bash

- name: Manage the public SSH keys on GitHub server for {{ user.name }}
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    key: https://github.com/{{ github_id }}.keys
  loop: "{{ user.ssh_import_id | map('regex_replace', '^gh:(.*)$', '\\1') | list }}"
  when: user.ssh_import_id is defined
  loop_control:
    loop_var: github_id
