- name: Install dependencies
  ansible.builtin.package:
    name:
      - quota
    state: present
  when: automated_config_home_enable_quotas

- name: Mount up device where HOME resides
  ansible.posix.mount:
    path: "{{ automated_config_home_mount_point }}"
    src: "{{ automated_config_home_mount_device }}"
    fstype: "{{ automated_config_home_mount_fstype }}"
    opts: "{{ automated_config_home_mount_options }}"
    state: mounted
  when: automated_config_home_enable_quotas

- name: Remount a mounted volume
  ansible.posix.mount:
    path: "{{ automated_config_home_mount_point }}"
    state: remounted

- name: Manage user quotas
  ansible.builtin.include_tasks:
    file: single_user.yml
  loop: "{{ automated_config_users }}"
  loop_control:
    loop_var: user
  when: automated_config_home_enable_quotas
