- name: Install dependencies
  ansible.builtin.package:
    name:
      - quota
    state: present
  when: automated_config_home_enable_quotas

- name: Mount up device by UUID
  ansible.posix.mount:
    path: "{{ automated_config_home_directory | default('/home')}}"
    src: "{{ automated_config_home_src | default('ext4')}}"
    fstype: "{{ automated_config_home_fstype | default('ext4')}}"
    opts: defaults,nofail,discard,usrquota,grpquota
    state: mounted
  when: automated_config_home_enable_quotas

- name: Manage user quotas
  ansible.builtin.include_tasks:
    file: single_user.yml
  loop: "{{ automated_config_users }}"
  loop_control:
    loop_var: user
  when: automated_config_home_enable_quotas
