- name: Install dependencies
  ansible.builtin.package:
    name:
      - ssh-import-id
    state: present

- name: Ensure users directory exists
  ansible.builtin.file:
    path: "{{ automated_config_home_directory | default('/home') }}"
    mode: "{{ automated_config_directory_mode | default('0755') }}"
    state: directory

- name: Manage usergroups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ automated_config_groups }}"

- name: Manage users
  ansible.builtin.include_tasks:
    file: single_user.yml
  loop: "{{ automated_config_users }}"
  loop_control:
    loop_var: user
