- name: Manage usergroups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ config.groups }}"

- name: Manage users
  ansible.builtin.include_tasks:
    file: single_user.yml
  loop: "{{ config.users }}"
  loop_control:
    loop_var: user
