- name: Gather all VMs from the cluster folder
  community.vmware.vmware_vm_info:
    folder: "{{ vcenter_datacenter }}/vm/{{ vm_cluster_name }}"
  delegate_to: localhost
  register: vm_info

- name: Power-off all machines gathered
  community.vmware.vmware_guest:
    uuid: "{{ item.uuid }}"
    state: powered-off
  loop: "{{ vm_info.virtual_machines }}"

- name: Destroy the cluster gathered
  community.vmware.vmware_guest:
    uuid: "{{ item.uuid }}"
    state: absent
  loop: "{{ vm_info.virtual_machines }}"

- name: Destroy the cluster folder
  community.vmware.vcenter_folder:
    datacenter_name: "{{ vcenter_datacenter }}"
    folder_name: "{{ vm_cluster_name }}"
    folder_type: vm
    state: absent
  delegate_to: localhost
