---
- name: Harden ssh configuration
  hosts: localhost

  tasks:
    - name: Ensure the sshd privilege separation directory exists
      become: true
      ansible.builtin.file:
        path: "/run/sshd"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Harden SSH configuration
      ansible.builtin.include_role:
        name: devsec.hardening.ssh_hardening
      vars:
        sshd_authenticationmethods: publickey
