---
- name: Destro virtual guests
  hosts: localhost
  become: true
  connection: local

  tasks:
    - name: Destroy virtual machines
      ansible.builtin.include_role:
        name: bouncmpe.automated.destroy_libvirt_guest
