# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/group_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html
---
- name: Ensure primary user group exists
  ansible.builtin.group:
    name: "{{ primary_group | default(username) }}"
    state: "{{ state }}"

- name: Manage the user {{ username }}
  ansible.builtin.user:
    name: "{{ username }}"
    home: "{{ users_home }}/{{ username }}"
    group: "{{ primary_group | default(username) }}"
    groups: "{{ usergroups }}"
    state: "{{ state }}"
    remove: "{{ remove }}"
    append: false
    generate_ssh_key: true
    ssh_key_type: "ed25519"
    ssh_key_file: ".ssh/id_ed25519"
    password_lock: true
    create_home: true

- name: Manage the public SSH keys on GitHub server for {{ username }}
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: "{{ state }}"
    key: https://github.com/{{ github_id }}.keys
  loop: "{{ ssh_import_id | map('regex_replace', '^gh:(.*)$', '\\1') | list }}"
  loop_control:
    loop_var: github_id
