- name: Force stop virtual guests using libvirt
  ansible.builtin.shell: >-
    virsh destroy "{{ guest.inventory_hostname }}"
  when: not guest.inventory_hostname in libvirt_guest_list_inactive

- name: Delete virtual guests using libvirt
  ansible.builtin.shell: >-
    virsh undefine "{{ guest.inventory_hostname }}" --remove-all-storage --wipe-storage
