#cloud-config
timezone: Europe/Istanbul
package_update: true
packages:
  - git
  - cron
users:
  - name: local_admin
    passwd: $6$rounds=4096$Qtx7ihKggIa$Qv4vT91F6bdAt78hYoGsA4R215dDjIBZgRw7wkC5mkrXvdjnZ7DgT7lKKsolz9it7c1xVOJPmUpn3SzaWG3Zi.
    lock_passwd: false
    groups: sudo
    shell: /bin/bash

  - name: bouncmpe
    groups: sudo
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_import_id:
      - gh:doganulus
